- hosts: "all"
  vars_files:
    - ~/ansible/vars/main.yml
  become: "yes"
  tasks:

  - name: Install fail2ban (Debian).
    package:
      name: fail2ban
      state: present
    when: ansible_os_family == 'Debian'


  - name: Setup fail2ban configuration.
    template:
      src: "{{ fail2ban_configuration_template }}"
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644


  - name: Ensure fail2ban is running and enabled on boot.
    service:
      name: fail2ban
      state: started
      enabled: true
